### ISSUE TITLE
Extension fails to load

### ISSUE THREAD

**Issue by aidan-j-rhoden** [nlaha/godot-midi-4.0#3]
I don't know what versions you are targeting, so this may not even be relevant.  I would like to use this extension for the latest builds of Godot; is there any way I can help with this?

These are the errors I get upon import:
<img width="480" alt="image" src="https://github.com/nlaha/godot-midi-4.0/assets/70079907/0880fa55-ddae-4acd-9769-6d4bab81c4a0">
The error message `Failed to load script "res//addons/godot_midi/godot_midi.gd" with error "Compilation failed".` also pops up at the beginning.

**Debug info:**
* OS: MacOS 12.6.8 (up to date)
* Godot version: 4.0.4.official, 4.1.1.official, 4.2.dev3.official

**Comment by aidan-j-rhoden** [comment]
In 4.0, the extension is available to enable in the project settings, but it still has the same errors.  In 4.1 and 4.2, it's not even visible.

**Comment by bits-by-brandon** [comment]
Experiencing this same issue.

```
core/extension/gdextension.cpp:593 - GDExtension configuration file must contain a "configuration/compatibility_minimum" key: res://bin/godotmidi.gdextension
  Failed loading resource: res://bin/godotmidi.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
  res://addons/godot_midi/midi_import_plugin.gd:40 - Parse Error: Identifier "Midi" not declared in the current scope.
```

- Godot v4.1.1.stable.official [bd6af8e0e]
- OS: MacOS 13.4

**Comment by bits-by-brandon** [comment]
After adding the required key
`compatibility_minimum = 4.1`
I have a new error:

```
Can't open dynamic library: /Users/*********/bin/godotmidi/libgdgodotmidi.macos.template_debug.framework. Error: dlopen(/Applications/Godot.app/Contents/MacOS/../Frameworks/libgdgodotmidi.macos.template_debug.framework, 0x0002): tried: '/Applications/Godot.app/Contents/MacOS/../Frameworks/libgdgodotmidi.macos.template_debug.framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Godot.app/Contents/MacOS/../Frameworks/libgdgodotmidi.macos.template_debug.framework' (no such file), '/Applications/Godot.app/Contents/MacOS/../Frameworks/libgdgodotmidi.macos.template_debug.framework' (no such file).
  core/extension/gdextension.cpp:455 - GDExtension dynamic library not found: /Users/***********/bin/godotmidi/libgdgodotmidi.macos.template_debug.framework
  Failed loading resource: res://bin/godotmidi.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
  res://addons/godot_midi/midi_import_plugin.gd:40 - Parse Error: Identifier "Midi" not declared in the current scope.
```

**Comment by nlaha** [comment]
Hi, sorry for the delay in getting back to you, I assume you probably used the precompiled binaries as the README instructs. Unfortunately, that version was only built for Windows and is also quite old. I triggered a new build on GitHub actions for all platforms and will post the updated binaries once it finishes (usually takes 2+ hours).

You can see the progress and download the binaries here:
https://github.com/nlaha/godot-midi-4.0/actions/runs/6280459658

I'll post them under releases when it finishes.

**Comment by aidan-j-rhoden** [comment]
Yes, you are correct.
Thank you so much for getting that set up!

**Comment by aidan-j-rhoden** [comment]
This has been fixed with the latest release.
